export const accents = {
  pink: {
    text: "text-pink",
    bg: "bg-pink",
    bgSoft: "bg-pink-softer",
    border: "border-pink",
    borderSoft: "border-pink-soft",
    ring: "ring-pink",
  },
  amber: {
    text: "text-amber",
    bg: "bg-amber",
    bgSoft: "bg-amber-softer",
    border: "border-amber",
    borderSoft: "border-amber-soft",
    ring: "ring-amber",
  },
  green: {
    text: "text-green",
    bg: "bg-green",
    bgSoft: "bg-green-softer",
    border: "border-green",
    borderSoft: "border-green-soft",
    ring: "ring-green",
  },
  teal: {
    text: "text-teal",
    bg: "bg-teal",
    bgSoft: "bg-teal-softer",
    border: "border-teal",
    borderSoft: "border-teal-soft",
    ring: "ring-teal",
  },
  purple: {
    text: "text-lilac-light",
    bg: "bg-purple",
    bgSoft: "bg-purple-softer",
    border: "border-purple",
    borderSoft: "border-purple-soft",
    ring: "ring-purple",
  },
};
